### PR TITLE
warnings: fix format-security warnings

### LINKED ISSUE #245: Failed to compile with `clang++`
Trying to compile ImHex 1.8 using `clang++`. It fails with the error: `/var/tmp/pamac-build-kibouo/imhex/src/imhex/source/views/view_hexeditor.cpp:305:32: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]`. (See attached log for complete output.)

Info: 
- [AUR package 1.8.1-1](https://aur.archlinux.org/packages/imhex),
- `clang++`: 
image

[compile.log](https://github.com/WerWolv/ImHex/files/6546632/compile.log)

### PR DESCRIPTION
**Pull request by russkel**
Manjaro and presumably other systems have started adding the `-Werror=format-security` flag, causing the build to fail.

It might make sense to add the `-Werror=format-security` flag to the compiler flags given how easy it is to keep it happy.

Fixes #245 and #295

### CODE REVIEW

**Comment by WerWolv** [comment]
Thank you!
I assumed the issue was caused by the `%llx` vs. `%lx` warnings I've given up on fixing instead of this.

File: source/views/view_help.cpp [hunk 1]
```diff
@@ -27,15 +27,15 @@ namespace hex {
...
-        ImGui::TextColored(ImVec4(0.57F, 0.24F, 0.69F, 1.0F), name.c_str());
+        ImGui::TextColored(ImVec4(0.57F, 0.24F, 0.69F, 1.0F), "%s", name.c_str());
         ImGui::SameLine();
-        ImGui::TextColored(ImVec4(0.71F, 0.19F, 0.31F, 1.0F), "(");
+        ImGui::TextColored(ImVec4(0.71F, 0.19F, 0.31F, 1.0F), "%s", "(");
         ImGui::SameLine();
         ImGui::Text("%s", arguments.c_str());
         ImGui::SameLine();
-        ImGui::TextColored(ImVec4(0.71F, 0.19F, 0.31F, 1.0F), ")");
+        ImGui::TextColored(ImVec4(0.71F, 0.19F, 0.31F, 1.0F), "%s", ")");
```
Comment (WerWolv) [inline source/views/view_help.cpp:38]: Are these two lines really giving off warnings too?

Comment (WerWolv) [reply source/views/view_help.cpp:38]: I meant the ones with only `"("` and  `")"` as the string. Mobile might have messed up something sorry

Comment (russkel) [reply source/views/view_help.cpp:38]: Oh sorry, it doesn't look like it actually. I can revert those lines.

Comment (WerWolv) [reply source/views/view_help.cpp]: Great thanks :)

**Comment by russkel** [comment]
I don't think "%s" is working for the `LangEntry` lines.

The warning is correct:
```
/home/russ/aur/imhex/src/imhex/source/views/view_help.cpp: In member function ‘void hex::ViewHelp::drawAboutPopup()’:
/home/russ/aur/imhex/src/imhex/source/views/view_help.cpp:80:34: warning: format ‘%s’ expects argument of type ‘char*’, but argument 2 has type ‘hex::LangEntry’ [-Wformat=]
   80 |             ImGui::TextWrapped("%s", "hex.view.help.about.thanks"_lang);
      |                                 ~^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                  |   |
      |                                  |   hex::LangEntry
      |                                  char*
```

**Comment by WerWolv** [comment]
I love C generics... You need to explicitly static_cast the value to a const char* for the conversation operator to be called correctly

**Comment by russkel** [comment]
> I love C generics... You need to explicitly static_cast the value to a const char* for the conversation operator to be called correctly

That worked, but damn it's ugly. Should I fix up the others and push changes?

**Comment by WerWolv** [comment]
Yes please.
Yeah I don't think there's really a better way besides wrapping the ImGui calls into proper C++ variadic functions. Either way it's going to be ugly

**Comment by russkel** [comment]
As master isn't compiling for me, I cherry-picked the patch onto `v1.9.0` (https://github.com/russkel/ImHex/tree/v1.9.0) and compiled it on Manjaro. Seems to be working well.
